# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d178c6b2579497900ce390b260109a66"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true
name = "CTX checkout review"

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_metafields,read_metafields"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[build]
automatically_update_urls_on_dev = true
